{
 "title": "Synthetic Checks",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "1 - check_status_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(check_duration_ms_bucket[5m])) by (name,le))"
    }
   ]
  },
  {
   "title": "Average response time ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "check_duration_ms_sum / check_duration_ms_count",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}